azure-devops/app-projects/05_tlscert-dev-api-dev-platform-pagopa-it.tf, azure-devops/app-projects/05_tlscert-dev-config-dev-plaform-pagopa-it.tf, azure-devops/app-projects/05_tlscert-dev-dev-checkout-pagopa-it.tf, azure-devops/app-projects/05_tlscert-dev-management-dev-platform-pagopa-it.tf, azure-devops/app-projects/05_tlscert-dev-portal-dev-platform-pagopa-it.tf, azure-devops/app-projects/05_tlscert-prod-api-platform-pagopa-it.tf, azure-devops/app-projects/05_tlscert-prod-checkout-pagopa-it.tf, azure-devops/app-projects/05_tlscert-prod-config-prod-plaform-pagopa-it.tf, azure-devops/app-projects/05_tlscert-prod-management-platform-pagopa-it.tf, azure-devops/app-projects/05_tlscert-prod-portal-platform-pagopa-it.tf, azure-devops/app-projects/05_tlscert-uat-api-uat-platform-pagopa-it.tf, azure-devops/app-projects/05_tlscert-uat-config-uat-plaform-pagopa-it.tf, azure-devops/app-projects/05_tlscert-uat-management-uat-platform-pagopa-it.tf, azure-devops/app-projects/05_tlscert-uat-portal-uat-platform-pagopa-it.tf, azure-devops/app-projects/05_tlscert-uat-uat-checkout-pagopa-it.tf
added triggers to tls pipelines
allow triggers to tls cert
---
=> added trigger

.github/workflows/static_analysis.yml, .pre-commit-config.yaml
=> fix: Update pre-commit image

azure-devops/app-projects/03_service_connections_github.tf, azure-devops/app-projects/99_variables.tf
=> chore: Add sonar service connection id

azure-devops/app-projects/06_pagopa-api-config.tf, azure-devops/app-projects/99_variables.tf, azure-devops/iac-projects/README.md
- update container registry for API Config project
---
=> breaking: Update container registry for API Config

azure-devops/shared-projects/06_pagopa-iuv-generator-service.tf
=> feat: [IUVGenerator] Fix deploy pipeline var

azure-devops/app-projects/03_service_connections_tls_certificate.tf, azure-devops/shared-projects/06_pagopa-iuv-generator-service.tf
=> feat: [IUVGenerator] var pipeline

azure-devops/iac-projects/.terraform.lock.hcl, azure-devops/iac-projects/04_iac.tf, azure-devops/iac-projects/05_backups.tf, azure-devops/iac-projects/99_variables.tf
=> Pipeline to backup apim

azure-devops/iac-projects/05_backups.tf
=> Fix schedule branch filter

azure-devops/iac-projects/.terraform.lock.hcl, azure-devops/iac-projects/01_project.tf, azure-devops/iac-projects/05_backups.tf
=> Apim backup in business hours

azure-devops/afm-projects/06_pagopa-afm-calculator-service.tf, azure-devops/afm-projects/06_pagopa-afm-marketplace-be-service.tf
=> fix path afm pipelines

azure-devops/afm-projects/06_pagopa-afm-calculator-data-service.tf
added pipelines CI/CD ( only DEV) for a new microservice
---
=> [AFM] Added calculator-data pipeline

azure-devops/app-projects/06_pagopa-api-config-fe.tf
=> fix cd apiconfig FE

azure-devops/iac/04_iac_core.tf
- updated triggers for core
- updated triggers for core
---
=> fix: Triggers for core

azure-devops/afm/.terraform.lock.hcl, azure-devops/afm/03_service_connections_appinsights_dev.tf, azure-devops/afm/06_pagopa-afm-calculator-service.tf, azure-devops/afm/99_variables.tf, azure-devops/afm/README.md
=> fix: Upd afm calculator service CD pipelines vars

azure-devops/shared/06_pagopa-notifications-service.tf
=> feat: CHK-615 Service connection for notification service uat/prod

azure-devops/afm/03_service_connections_appinsights_uat.tf, azure-devops/afm/06_pagopa-afm-calculator-data-service.tf, azure-devops/afm/06_pagopa-afm-calculator-service.tf, azure-devops/afm/06_pagopa-afm-marketplace-be-service.tf, azure-devops/afm/99_variables.tf, azure-devops/afm/README.md
=> feat: PGEC-53 UAT AFM

azure-devops/afm/06_pagopa-afm-marketplace-be-service.tf
=> feat: AFM added var

azure-devops/afm/06_pagopa-afm-calculator-data-service.tf
- added prod_container_registry_service_conn
---
=> feat: Added prod_container_registry_service_conn

azure-devops/gps/.terraform.lock.hcl, azure-devops/gps/03_service_connections_appinsights.tf, azure-devops/gps/06_pagopa-gps-donation-service.tf, azure-devops/gps/06_pagopa-reporting-orgs-enrollment.tf, azure-devops/gps/06_pagopa-spontaneous-payments.tf, azure-devops/gps/99_variables.tf, azure-devops/gps/README.md, azure-devops/shared/.terraform.lock.hcl, azure-devops/shared/03_service_connections_appinsights.tf, azure-devops/shared/06_pagopa-iuv-generator-service.tf, azure-devops/shared/99_variables.tf, azure-devops/shared/README.md
=> feat: Add ai connection to gps shared prj

azure-devops/app/06_pagopa-assets-platform.tf
=> fix: Service connection for assets

azure-devops/ecommerce/06_pagopa-ecommerce-payment-requests-service.tf
=> feat: New pipeline payment requests

azure-devops/app/06_pagopa-node-forwarder.tf
=> fix ci pagopa-node-forwarder

azure-devops/bizevents/00_secrets_bizevents.tf, azure-devops/bizevents/03_service_connections_aks.tf, azure-devops/bizevents/03_service_connections_appinsights.tf, azure-devops/bizevents/06_pagopa-biz-events-datastore-service.tf, azure-devops/bizevents/README.md
=> uat bizevent

azure-devops/selfcare/10_pagopa-selfcare-backoffice-backend.tf
=> fix: Selfcare uat env pipelines

azure-devops/bizevents/00_secrets_bizevents.tf, azure-devops/bizevents/06_pagopa-biz-events-datastore-service.tf, azure-devops/bizevents/06_pagopa-biz-events-service-service.tf
=> chore: Enable UAT deploy

azure-devops/app/06_pagopa-node-forwarder.tf
=> feat: perf pipeline fix

azure-devops/bizevents/06_pagopa-biz-events-service-service.tf
- move secret in deploy module
---
=> fix: biz-events-service-secret

azure-devops/afm/00_secrets_afm.tf, azure-devops/afm/06_pagopa-afm-calculator-service.tf
added 2 secrets for `performance test` pipeline
---
=> new secrets

azure-devops/.env/nodo_state.tfvars, azure-devops/nodo/.terraform.lock.hcl, azure-devops/nodo/00_key_vault.tf, azure-devops/nodo/00_secrets_nodo.tf, azure-devops/nodo/00_secrets_prod.tf, azure-devops/nodo/01_project.tf, azure-devops/nodo/03_service_connections_aks.tf, azure-devops/nodo/03_service_connections_appinsights.tf, azure-devops/nodo/03_service_connections_tls_certificate.tf, azure-devops/nodo/05_tlscert-weudev-nodo-internal-dev-platform-pagopa-it.tf, azure-devops/nodo/06_pagopa-nodo-service.tf, azure-devops/nodo/99_main.tf, azure-devops/nodo/99_variables.tf, azure-devops/nodo/README.md
=> feat: Nodo pipeline prj

azure-devops/app/06_pagopa-node-forwarder.tf
- fix variables for production env
---
=> feat: PAGOPA-389 fix deploy for prod

azure-devops/gps/.terraform.lock.hcl, azure-devops/gps/00_secrets_gps.tf, azure-devops/gps/06_pagopa-gpd-payments.tf
Co-authored-by: Angelo Caporaso <AngeloCaporaso@users.noreply.github.com>
Co-authored-by: Andrea De Rinaldis <andrea-deri@users.noreply.github.com>
Adding the necessary subkeys for the correct behavior of the system
The subkeys are needed for the application to work properly
---
=> PAGOPA-600 subkey generation

azure-devops/gps/00_secrets_gps.tf, azure-devops/gps/06_pagopa-gpd-payments.tf
- Set payments SOAP and REST subscription key for pipelines execution in DEV and UAT
---
=> PAGOPA-600 split payments subscription keys

azure-devops/nodo/06_pagopa-nodo-service.tf
=> add-dev_container_registry_service_conn-deploy_nodo

azure-devops/nodo/06_pagopa-nodo-service.tf
=> uncomment-image_repository_name

azure-devops/nodo/06_pagopa-nodo-service.tf, azure-devops/nodo/06_pagopa-web-bo-service.tf
=> fix: Mail bot

azure-devops/nodo/06_pagopa-nodo-service.tf, azure-devops/nodo/README.md
=> fix: Code Review nodo

azure-devops/nodo/06_pagopa-nodo-service.tf
=> feat: NOD-32 NDP integration pipe

azure-devops/nodo/06_pagopa-nodo-service.tf
=> fix: Pipe test integ nodo

azure-devops/nodo/00_key_vault.tf, azure-devops/nodo/03_service_connections_tls_certificate.tf, azure-devops/nodo/05_tlscert-weuuat-nodo-internal-uat-platform-pagopa-it.tf, azure-devops/nodo/06_pagopa-nodo-service.tf, azure-devops/nodo/README.md
=> feat: Add weuuat nodo internal tls pipe

azure-devops/nodo-cron/00_key_vault.tf, azure-devops/nodo-cron/00_secrets_nodo.tf, azure-devops/nodo-cron/03_service_connections_aks.tf, azure-devops/nodo-cron/03_service_connections_appinsights.tf, azure-devops/nodo-cron/06_pagopa-nodo-service-cron.tf, azure-devops/nodo-cron/README.md
=> feat: Aggiunte tf conf per UAT

azure-devops/nodo/06_pagopa-api-config-service.tf
- enabled pipeline for UAT env
---
=> feat: Enabled UAT Pipeline for API-CFG

azure-devops/iac/04_iac_nodo.tf
=> add: Prod iac nodo perm

azure-devops/iac/04_iac_nodo.tf, azure-devops/nodo/00_secrets_nodo.tf, azure-devops/nodo/03_service_connections_aks.tf, azure-devops/nodo/06_pagopa-api-config-service.tf, azure-devops/nodo/06_pagopa-firmatore-service.tf, azure-devops/nodo/06_pagopa-nodo-service.tf, azure-devops/nodo/06_pagopa-web-bo-service.tf, azure-devops/nodo/06_pagopa-wfesp-service.tf, azure-devops/nodo/README.md
=> feat: Fix nodo prod

azure-devops/ecommerce/06_pagopa-ecommerce-transactions-functions.tf
=> feat: Add sc for fn-ecommerce

azure-devops/nodo/06_pagopa-nodo-service.tf
=> fix : Add vars for suspend job pipe

azure-devops/nodo/06_pagopa-firmatore-service.tf
=> feat: Fix namespace

azure-devops/ecommerce/00_secrets_ecommerce.tf, azure-devops/ecommerce/06_pagopa-ecommerce-notifications-service.tf
=> feat: Add env for testing notifications

azure-devops/app/00_secrets_dev.tf, azure-devops/app/00_secrets_uat.tf, azure-devops/app/06_pagopa-debt-position.tf
Added the perf test pipeline for the gpd project
This addition is required for the performance report on gpd
---
=> feat: Creating gpd perf test pipeline PAGOPA-705

azure-devops/afm/00_secrets_afm.tf, azure-devops/afm/06_pagopa-afm-calculator-service.tf
- COSMOS_SUBSCRIPTION_KEY addition in DEV and UAT to use cosmos client in performance test
---
=> feat: Add performance test variable in AFM domain PAGOPA-706

azure-devops/nodo/06_pagopa-mock-ec-prf-service.tf, azure-devops/nodo/06_pagopa-mock-ec-service.tf, azure-devops/nodo/06_pagopa-mock-pm-service.tf, azure-devops/nodo/06_pagopa-mock-psp-prf-service.tf, azure-devops/nodo/06_pagopa-mock-psp-service.tf
=> feat: NOD-101: Housekeeping UAT, NOD-102: HouseKeeping DEV

azure-devops/app/06_pagopa-debt-position.tf
Adding keys for integrations tests of gpd
Needed to perform calls to gpd from deploy pipeline
---
=> feat: Adding key for integration tests PAGOPA-737

azure-devops/nodo/00_secrets_nodo.tf, azure-devops/nodo/06_pagopa-nodo-service.tf
[Nodo] Licenza lightbend
Added missing variables for code review and deploy pipeline
---
=> feat: NOD-143 missing variables for uat and prod

azure-devops/.env/fdr_state.tfvars, azure-devops/fdr/.terraform.lock.hcl, azure-devops/fdr/00_key_vault.tf, azure-devops/fdr/00_secrets_fdr.tf, azure-devops/fdr/00_secrets_prod.tf, azure-devops/fdr/01_project.tf, azure-devops/fdr/03_service_connections_aks.tf, azure-devops/fdr/03_service_connections_appinsights.tf, azure-devops/fdr/03_service_connections_tls_certificate.tf, azure-devops/fdr/05_tlscert-weudev-fdr-internal-dev-platform-pagopa-it.tf, azure-devops/fdr/05_tlscert-weuprod-fdr-internal-platform-pagopa-it.tf, azure-devops/fdr/05_tlscert-weuuat-fdr-internal-platform-pagopa-it.tf, azure-devops/fdr/06_pagopa-fdr-service.tf, azure-devops/fdr/99_main.tf, azure-devops/fdr/99_variables.tf, azure-devops/fdr/README.md
=> feat: NOD-154 cicd FdR

azure-devops/apiconfig/00_secrets_apiconfig.tf, azure-devops/apiconfig/03_service_connections_aks.tf, azure-devops/apiconfig/03_service_connections_appinsights.tf, azure-devops/apiconfig/06_pagopa-api-config-selfcare-integration-service.tf, azure-devops/apiconfig/README.md
- added files for api-config-selfcare-integration
- activity related to the creation of the new repository api-config-selfcare-integration
---
=> [PAGOPA-759] devops: added conf file for api-config-selfcare-integration

azure-devops/fdr/06_pagopa-fdr-nodo-service.tf
=> feat: NOD-195: creazione devops, build and deploy con helm

azure-devops/iac/04_iac_wallet.tf
=> feat: CHK-1406 Add iac pipeline for wallet

azure-devops/iac/00_secrets_kv_wallet.tf, azure-devops/iac/04_iac_wallet.tf, azure-devops/iac/99_variables.tf
=> feat: Chk 1406 iac wallet

azure-devops/fdr/00_secrets_fdr.tf, azure-devops/fdr/03_service_connections_aks.tf, azure-devops/fdr/03_service_connections_appinsights.tf, azure-devops/fdr/06_pagopa-fdr-nodo-service.tf, azure-devops/fdr/README.md
Allineata ed abilitata la configurazione di uat sulla falsa riga di quella di dev 
---
=> feat: NOD-233 DEVOPS fdr allineare uat con dev

azure-devops/iac/04_iac_checkout.tf
=> feat: CHK-1447 Add iac pipeline for checkout

azure-devops/app/05_tlscert-prod-api-platform-pagopa-it.tf, azure-devops/app/05_tlscert-prod-checkout-pagopa-it.tf, azure-devops/app/05_tlscert-prod-config-prod-plaform-pagopa-it.tf, azure-devops/app/05_tlscert-prod-management-platform-pagopa-it.tf, azure-devops/app/05_tlscert-prod-portal-platform-pagopa-it.tf
To avoid 
```
File "/home/vsts/.local/lib/python3.8/site-packages/azure/identity/_internal/client_credential_base.py", line 42, in _request_token
raise ClientAuthenticationError(message=message)
azure.core.exceptions.ClientAuthenticationError: Authentication failed: AADSTS7000222: The provided client secret keys for app '***' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds.
Trace ID: a27d12d1-7142-4440-a9df-eb2bec820d00
Correlation ID: caa910b2-22b5-4b1a-991a-0f4be44824aa
Timestamp: 2023-05-15 05:01:19Z
```
force renew token pipelines
ℹ️ to details errore see [here](https://dev.azure.com/pagopaspa/pagoPA-projects/_build/results?buildId=93429&view=logs& …
=> fix: Renew token cert pipe 

azure-devops/apiconfig/00_secrets_apiconfig.tf, azure-devops/apiconfig/03_service_connections_aks.tf, azure-devops/apiconfig/06_pagopa-api-config-cache-service.tf, azure-devops/apiconfig/README.md
- enabled prod configuration
---
=> feat: [NOD-261] APIConfig Cache - prod env

azure-devops/apiconfig/00_secrets_apiconfig.tf, azure-devops/apiconfig/06_pagopa-api-config-cache-service.tf
=> fix : ApiCfg cache deploy prod

azure-devops/app/05_tlscert-dev-api-dev-platform-pagopa-it.tf, azure-devops/app/05_tlscert-dev-config-dev-plaform-pagopa-it.tf, azure-devops/app/05_tlscert-dev-management-dev-platform-pagopa-it.tf, azure-devops/app/05_tlscert-dev-portal-dev-platform-pagopa-it.tf
=> fix: Apim DEV cert

azure-devops/.env/receipts_state.tfvars, azure-devops/receipts/.terraform.lock.hcl, azure-devops/receipts/00_key_vault.tf, azure-devops/receipts/00_secrets_prod.tf, azure-devops/receipts/00_secrets_receipts.tf, azure-devops/receipts/01_project.tf, azure-devops/receipts/03_service_connections_aks.tf, azure-devops/receipts/03_service_connections_appinsights.tf, azure-devops/receipts/03_service_connections_tls_certificate.tf, azure-devops/receipts/05_tlscert-weudev-receipts-internal-dev-platform-pagopa-it.tf, azure-devops/receipts/05_tlscert-weuprod-receipts-internal-platform-pagopa-it.tf, azure-devops/receipts/05_tlscert-weuuat-receipts-internal-uat-platform-pagopa-it.tf, azure-devops/receipts/99_main.tf, azure-devops/receipts/99_variables.tf, azure-devops/receipts/README.md
=> feat: Add cert receipts.internal

azure-devops/iac/00_secrets_kv_ecommerce.tf, azure-devops/iac/04_iac_ecommerce.tf
=> feat(ecommerce): CHK-1538 enable aks param for prod

azure-devops/mock/.terraform.lock.hcl, azure-devops/mock/README.md, azure-devops/shared/06_pagopa-platform-authorizer-service.tf
=> feat: Auth in prod

azure-devops/nodo/06_pagopa-nodo-service.tf
=> fix var name deploy pool of nodo

azure-devops/gps/06_pagopa-gpd-debt-position.tf
- The module and variables related to the GPD-core code review pipeline were removed
- The pipeline was migrated from Azure DevOps to GitHub Actions in [this](https://github.com/pagopa/pagopa-debt-position/pull/160) pull request.
---
=> chore: Remove code-review pipeline for GPD-core [PAGOPA-1039]

azure-devops/receipts/00_secrets_receipts.tf, azure-devops/receipts/06_pagopa-receipts-data-store.tf, azure-devops/receipts/README.md
=> feat: Add perf pipe receipts

azure-devops/iac/00_secrets_kv_ecommerce.tf, azure-devops/iac/04_iac_ecommerce.tf
Depends on https://github.com/pagopa/pagopa-infra/pull/1183
Add secret for invoke gha from ecommerce IAC deploy pipeline
Add secret for invoke gha from ecommerce IAC deploy pipeline
---
=> feat(iac-ecommerce-app): CHK-1723 add secret for dashboard creation

azure-devops/apiconfig/05_tlscert-weudev-apiconfig-internal-dev-platform-pagopa-it.tf, azure-devops/apiconfig/05_tlscert-weuprod-apiconfig-internal-platform-pagopa-it.tf, azure-devops/apiconfig/05_tlscert-weuuat-apiconfig-internal-platform-pagopa-it.tf
=> fix: Tls apiconfig

azure-devops/nodo/06_pagopa-nodo-re-to-tablestorage.tf
=> [NOD-410] Fix CD pipeline

azure-devops/ecommerce/00_secrets_ecommerce.tf, azure-devops/ecommerce/06_pagopa-ecommerce-helpdesk-service.tf
Configured api key into ecommerce-helpdesk deploy pipeline for execute test after deploy
Added new api-key configuration for execute tests
- [ x Update pipeline configuration
---
=> feat(configuration): CHK-1820 configure api key for deploy pipeline

azure-devops/iac/04_iac_switcher.tf
=> feat: Upgraded switcher, increased timeout

azure-devops/iac/04_iac_switcher.tf
=> feat: Excluded elastic from switcher

azure-devops/iac/04_iac_ecommerce.tf
Refacoring eCommerce IAC pipeline token secret
Refacoring eCommerce IAC pipeline token secret
---
=> fix(ecommerce-iac): Secret refactoring

azure-devops/qi/00_key_vault.tf, azure-devops/qi/00_secrets_qi.tf, azure-devops/qi/03_service_connections_aks.tf, azure-devops/qi/03_service_connections_tls_certificate.tf, azure-devops/qi/05_tlscert-weuuat-qi-internal-uat-platform-pagopa-it.tf, azure-devops/qi/README.md
=> feat: Add tls cert qi uat

azure-devops/receipts/06_pagopa-receipts-data-store.tf
Added blob storage conn string to datastore secrets
[Issue PRDP-136](https://pagopa.atlassian.net/browse/PRDP-136?atlOrigin=eyJpIjoiY2ViNTc1ZWE2ZTdhNDdlYjk3YzUzYjJmNTY4NmEzNzMiLCJwIjoiaiJ9)
---
=> [PRDP-136] Added blob storage conn string to datastore secrets

azure-devops/shared/00_secrets_shared.tf, azure-devops/shared/06_pagopa-pdf-engine-service.tf
- Added environment variable for pdf engine node subkey for  performace test
---
=> feat: Add env for pdf engine node subkey for  performace test

CODEOWNERS
=> feat: Update codeowner

azure-devops/receipts/03_service_connections_azure.tf, azure-devops/receipts/06_pagopa-receipts-generator.tf, azure-devops/receipts/README.md
=> feat: Add servic conn perf test receipts

azure-devops/wallet/06_pagopa-payment-wallet-fe.tf, azure-devops/wallet/README.md
- add new pipeline for payment wallet frontend only for dev and uat env
---
=> feat: CHK-1981 add new pipelines for wallet fe

azure-devops/checkout/00_secrets_prod.tf, azure-devops/checkout/06_pagopa-checkout-fe.tf
Added new api key into CR pipeline for checkout-fe.
---
=> feat(secret): CHK-1873  Added new secret into checkout-fe CR pipeline

azure-devops/qi/00_key_vault.tf, azure-devops/qi/00_secrets_prod.tf, azure-devops/qi/00_secrets_qi.tf, azure-devops/qi/03_service_connections_aks.tf, azure-devops/qi/03_service_connections_tls_certificate.tf, azure-devops/qi/05_tlscert-weuprod-qi-internal-platform-pagopa-it.tf, azure-devops/qi/README.md
=> feat: Add qi prod cert

azure-devops/aca/00_key_vault.tf, azure-devops/aca/00_secrets_aca.tf, azure-devops/aca/00_secrets_prod.tf, azure-devops/aca/03_service_connections_aks.tf, azure-devops/aca/03_service_connections_tls_certificate.tf, azure-devops/aca/05_tlscert-weuprod-wallet-internal-prod-platform-pagopa-it.tf, azure-devops/aca/06_pagopa-aca-service.tf, azure-devops/aca/README.md, azure-devops/iac/00_secrets_kv_aca.tf, azure-devops/iac/04_iac_aca.tf, azure-devops/iac/README.md
Added configuration to release aca into the production environment. 🚀
👉🏻 AKS configuration for PROD
👉🏻 TLS Certificate for PROD
👉🏻 IAC pipeline for PROD
La modifica è stata effettuata per configurare
---
=> feat: CHK-2066 added aca configuration for PROD 

azure-devops/aca/06_pagopa-aca-service.tf
Fixed deploy pipeline configuration for ACA
---
=> fix: deploy pipeline configuration

azure-devops/ecommerce/06_pagopa-ecommerce-for-io-tests.tf
=> fix: CHK-2056 ecommerce for io tests

azure-devops/ecommerce/06_pagopa-ecommerce-for-io-tests.tf
=> fix: CHK-2056 basepath for ecommerce for io tests

README.md, azure-devops/nodo/.terraform.lock.hcl, azure-devops/nodo/00_secrets_nodo.tf, azure-devops/nodo/00_secrets_prod.tf, azure-devops/nodo/03_service_connections_appinsights.tf, azure-devops/nodo/03_service_connections_tls_certificate.tf, azure-devops/nodo/05_tlscert-weudev-nodo-internal-dev-platform-pagopa-it.tf, azure-devops/nodo/05_tlscert-weuprod-nodo-internal-platform-pagopa-it.tf, azure-devops/nodo/05_tlscert-weuuat-nodo-internal-uat-platform-pagopa-it.tf, azure-devops/nodo/06_pagopa-firmatore-service.tf, azure-devops/nodo/06_pagopa-mock-ec-prf-service.tf, azure-devops/nodo/06_pagopa-mock-ec-service.tf, azure-devops/nodo/06_pagopa-mock-pm-service.tf, azure-devops/nodo/06_pagopa-mock-psp-prf-service.tf, azure-devops/nodo/06_pagopa-mock-psp-service.tf, azure-devops/nodo/06_pagopa-nodo-re-to-datastore.tf, azure-devops/nodo/06_pagopa-nodo-re-to-tablestorage.tf, azure-devops/nodo/06_pagopa-nodo-service.tf, azure-devops/nodo/06_pagopa-web-bo-service.tf, azure-devops/nodo/06_pagopa-wfesp-service.tf, azure-devops/nodo/99_main.tf, azure-devops/nodo/99_variables.tf
=> feat: Nodo migrated to managed identity

azure-devops/aca/.terraform.lock.hcl, azure-devops/aca/00_secrets_aca.tf, azure-devops/aca/00_secrets_prod.tf, azure-devops/aca/03_service_connections_tls_certificate.tf, azure-devops/aca/05_tlscert-weudev-wallet-internal-dev-platform-pagopa-it.tf, azure-devops/aca/05_tlscert-weuprod-wallet-internal-prod-platform-pagopa-it.tf, azure-devops/aca/05_tlscert-weuuat-wallet-internal-uat-platform-pagopa-it.tf, azure-devops/aca/06_pagopa-aca-load-tests.tf, azure-devops/aca/06_pagopa-aca-service.tf, azure-devops/aca/99_locals.tf, azure-devops/aca/99_main.tf
=> feat: Migrated aca managed identity

azure-devops/shared/.terraform.lock.hcl, azure-devops/shared/00_generic.tf, azure-devops/shared/00_secrets_prod.tf, azure-devops/shared/00_secrets_shared.tf, azure-devops/shared/03_service_connections_appinsights.tf, azure-devops/shared/06_pagopa-iuv-generator-service.tf, azure-devops/shared/06_pagopa-pdf-engine-service.tf, azure-devops/shared/06_pagopa-platform-authorizer-service.tf, azure-devops/shared/06_pagopa-poc-micronaut-service.tf, azure-devops/shared/06_pagopa-poc-quarkus-service.tf, azure-devops/shared/06_pagopa-taxonomy-fn.tf, azure-devops/shared/06_pagopa-tkm-mock-circuit.tf, azure-devops/shared/99_main.tf, azure-devops/shared/99_variables.tf, azure-devops/shared/README.md
=> feat: Migrate-shared

azure-devops/receipts/.terraform.lock.hcl, azure-devops/receipts/00_generic.tf, azure-devops/receipts/00_secrets_prod.tf, azure-devops/receipts/00_secrets_receipts.tf, azure-devops/receipts/03_service_connections_appinsights.tf, azure-devops/receipts/03_service_connections_azure.tf, azure-devops/receipts/03_service_connections_tls_certificate.tf, azure-devops/receipts/05_tlscert-weudev-receipts-internal-dev-platform-pagopa-it.tf, azure-devops/receipts/05_tlscert-weuprod-receipts-internal-platform-pagopa-it.tf, azure-devops/receipts/05_tlscert-weuuat-receipts-internal-uat-platform-pagopa-it.tf, azure-devops/receipts/06_pagopa-receipts-data-store.tf, azure-devops/receipts/06_pagopa-receipts-generator.tf, azure-devops/receipts/06_pagopa-receipts-notifier.tf, azure-devops/receipts/06_pagopa-receipts-service.tf, azure-devops/receipts/99_main.tf, azure-devops/receipts/99_variables.tf, azure-devops/receipts/README.md, azure-devops/wallet/05_tlscert-weudev-dev-payment-wallet-pagopa-it.tf, azure-devops/wallet/05_tlscert-weudev-wallet-internal-dev-platform-pagopa-it.tf, azure-devops/wallet/05_tlscert-weuuat-uat-payment-wallet-pagopa-it.tf, azure-devops/wallet/05_tlscert-weuuat-wallet-internal-uat-platform-pagopa-it.tf
=> feat: Receipts-migration

azure-devops/checkout/.terraform.lock.hcl, azure-devops/checkout/00_secrets_prod.tf, azure-devops/checkout/06_pagopa-checkout-fe.tf, azure-devops/checkout/06_pagopa-checkout-tests.tf, azure-devops/checkout/06_pagopa-functions-checkout.tf, azure-devops/checkout/06_pagopa-proxy.tf, azure-devops/checkout/99_locals.tf, azure-devops/checkout/99_main.tf, azure-devops/checkout/README.md
=> feat: Migrated checkout

azure-devops/fdr/.terraform.lock.hcl, azure-devops/fdr/00_secrets_fdr.tf, azure-devops/fdr/00_secrets_prod.tf, azure-devops/fdr/03_service_connections_appinsights.tf, azure-devops/fdr/03_service_connections_tls_certificate.tf, azure-devops/fdr/05_tlscert-weudev-fdr-internal-dev-platform-pagopa-it.tf, azure-devops/fdr/05_tlscert-weuprod-fdr-internal-platform-pagopa-it.tf, azure-devops/fdr/05_tlscert-weuuat-fdr-internal-uat-platform-pagopa-it.tf, azure-devops/fdr/06_pagopa-fdr-json-to-xml-fn.tf, azure-devops/fdr/06_pagopa-fdr-nodo-service.tf, azure-devops/fdr/06_pagopa-fdr-re-service.tf, azure-devops/fdr/06_pagopa-fdr-service.tf, azure-devops/fdr/06_pagopa-fdr-xml-to-json-fn.tf, azure-devops/fdr/99_locals.tf, azure-devops/fdr/99_main.tf, azure-devops/fdr/README.md
=> feat: Migrated fdr

.tfsec/tfsec.yml
=> chore: Added tfsec config file

azure-devops/wallet/00_secrets_wallet.tf, azure-devops/wallet/06_pagopa-wallet-service.tf
=> feat: CHK-2524 add key for migration testing

azure-devops/wallet/00_secrets_wallet.tf, azure-devops/wallet/06_pagopa-wallet-service.tf
=> feat: CHK-2524 add new token for migration test

azure-devops/printit/99_variables.tf
=> fix: Kubernetes itn changed service connection name

azure-devops/wallet/00_secrets_wallet.tf, azure-devops/wallet/06_pagopa-wallet-service.tf
=> fix: CHK-2576 Add cstar api key as environment variable key for integration tests

azure-devops/ecommerce/06_pagopa-ecommerce-for-io-tests.tf
add and update wallet token test variables for dev and uat
---
=> feat: CHK-2720 add wallet token test variables for dev and uat

azure-devops/iac/00_secrets_kv_paywallet.tf, azure-devops/iac/00_secrets_kv_printit.tf
=> fix:  Secrets reference

azure-devops/printit/00_key_vault.tf, azure-devops/printit/00_secrets_printit.tf, azure-devops/printit/00_service_connections.tf, azure-devops/printit/03_service_connections_aks.tf, azure-devops/printit/03_service_connections_tls_certificate.tf, azure-devops/printit/05_tlscert-printit-itn-internal-uat-platform-pagopa-it.tf, azure-devops/printit/README.md
=> chore: Add pipe for `itnuat.printit.internal.uat.platform.pagopa.it`

azure-devops/app/03_service_connections_docker.tf, azure-devops/app/README.md, azure-devops/pay-wallet/00_secrets_wallet.tf, azure-devops/pay-wallet/00_service_connections.tf, azure-devops/pay-wallet/03_service_connections_aks.tf, azure-devops/pay-wallet/06_pagopa-wallet-event-dispatcher-service.tf, azure-devops/pay-wallet/06_pagopa-wallet-service.tf, azure-devops/pay-wallet/README.md
- add configuration for pay-wallet prod pipelines.
---
=> feat(pay-wallet-pipeline): CHK-2946 enable prod pipelien for pay-wallet

azure-devops/printit/00_key_vault.tf, azure-devops/printit/00_secrets_printit.tf, azure-devops/printit/00_service_connections.tf, azure-devops/printit/03_service_connections_aks.tf, azure-devops/printit/06_pagopa-print-payment-notice-service.tf, azure-devops/printit/README.md
=> [printit] perf test configuration

azure-devops/app/06_pagopa-node-forwarder.tf
=> chore: Change app service name forwarder for HA

azure-devops/shared/00_service_connections.tf, azure-devops/shared/06_pagopa-pdf-engine-service.tf, azure-devops/shared/README.md
➕ added the variables for the Italian container registry to `pdf-engine`
to deploy in the new region
[VAS-1137](https://pagopa.atlassian.net/browse/VAS-1137)
---
[VAS-1137]: https://pagopa.atlassian.net/browse/VAS-1137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Container registry Italy to PDF-Engine [VAS-1137]

azure-devops/nodo/06_pagopa-mock-ec-service.tf
- Update AZDO deploy pipeline `mock-ec` for UAT environment
```
sh terraform.sh apply nodo 
```
Enable mock-ec in UAT
---
=> feat(nodo): Add AZDO mock-ec UAT

azure-devops/bizevents/00_secrets_bizevents.tf, azure-devops/bizevents/06_pagopa-biz-events-service-service.tf
=> feat: Upd pagopa-biz-events-service-service_performance_test

azure-devops/ecommerce/00_secrets_ecommerce.tf, azure-devops/ecommerce/06_pagopa-ecommerce-helpdesk-commands-service.tf
=> fix: added helpdesk command api key to deploy pipeline

azure-devops/nodo/06_pagopa-wisp-soap-converter-service.tf
Fixing repo in soap conv
Needed in order to point to the right repo
---
=> fix: solving repo error in perf test pipeline

azure-devops/aca/.terraform.lock.hcl, azure-devops/aca/99_main.tf, azure-devops/nodo/99_main.tf
=> fix: add `skip_provider_registration`  aca

azure-devops/mock/00_key_vault.tf, azure-devops/mock/00_secrets_mocker.tf, azure-devops/mock/00_service_connections.tf, azure-devops/mock/00_service_connections_workload_identity.tf, azure-devops/mock/03_service_connections_appinsights.tf, azure-devops/mock/06_pagopa-mock-ec-service.tf, azure-devops/mock/99_main.tf, azure-devops/mock/99_variables.tf, azure-devops/mock/README.md
Moving mock-ec pipeline from `nodo` to `mock` on k8s
Needed in order to retrieve the correct secrets
---
=> fix: moving deploy mock ec pipeline

azure-devops/gps/00_secrets_gps.tf, azure-devops/gps/06_pagopa-gpd-payments-pull.tf
- configured payments pull pipeline to run in PROD
[PPANTT-146](https://pagopa.atlassian.net/browse/PPANTT-146)
---
[PPANTT-146]: https://pagopa.atlassian.net/browse/PPANTT-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Configured prod env for payments pull performance pipeline

azure-devops/ecommerce/06_pagopa-ecommerce-helpdesk-service.tf
=> chore: PPABV-51 update helpdesk service testing config

azure-devops/ecommerce/00_secrets_ecommerce.tf
=> fix: mail testing

azure-devops/ebollo/00_secrets_ebollo.tf, azure-devops/ebollo/06_pagopa-gps-mbd-service.tf
- configured gps mbd performance test pipeline
[PPANTT-194](https://pagopa.atlassian.net/browse/PPANTT-194)
---
[PPANTT-194]: https://pagopa.atlassian.net/browse/PPANTT-194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [PPANTT-194] GPS MBD performance test pipeline

azure-devops/qi/00_service_connections_docker_workload_identity.tf, azure-devops/qi/06_pagopa-qi-fdr-kpi-service.tf, azure-devops/qi/99_main.tf, azure-devops/qi/99_variables.tf, azure-devops/qi/README.md
=> feat(pipeline-qi): add deploy config for pipeline (only DEV)

azure-devops/ebollo/00_secrets_ebollo.tf, azure-devops/ebollo/06_pagopa-mbd-service.tf
=> feat: updated performance test configs

azure-devops/ebollo/00_key_vault.tf, azure-devops/ebollo/00_secrets_ebollo.tf, azure-devops/ebollo/00_secrets_prod.tf, azure-devops/ebollo/00_service_connections.tf, azure-devops/ebollo/03_service_connections_aks.tf, azure-devops/ebollo/03_service_connections_tls_certificate.tf, azure-devops/ebollo/05_tlscert-ebollo-itn-internal-platform-pagopa-it.tf
=> add: Pipeline ebollo.itn.internal cert pipe

azure-devops/qi/06_pagopa-qi-fdr-kpi-service.tf
=> chore: Update fdr kpi code review pipeline

azure-devops/iac/04_iac_fdr.tf
- Changed FDR db pipelines repo path to [pagopa-fdr-nodo-dei-pagamenti](https://github.com/pagopa/pagopa-fdr-nodo-dei-pagamenti)
[PAGOPA-2663](https://pagopa.atlassian.net/browse/PAGOPA-2663?atlOrigin=eyJpIjoiMGJkODBmMGJiMjQzNDc4NzhhMDM0ZDFlNjE2NTk4NTEiLCJwIjoiaiJ9)
---
[PAGOPA-2663]: https://pagopa.atlassian.net/browse/PAGOPA-2663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PAGOPA-2663] chore: Migrate FDR db pipelines to pagopa-fdr-nodo-dei-pagamenti

azure-devops/iac/04_iac_fdr3.tf
- Defined fdr3 iac for db pipelines
[PAGOPA-2640](https://pagopa.atlassian.net/browse/PAGOPA-2640)
---
[PAGOPA-2640]: https://pagopa.atlassian.net/browse/PAGOPA-2640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [PAGOPA-2640] Define fdr3 iac for db pipelines

azure-devops/ecommerce/06_pagopa-ecommerce-fe.tf
=> chore: Add sonar for eCommerce fe

azure-devops/crusc8/05_tlscert-crusc8-dev-platform-pagopa-it.tf
=> add: Pipe cert crusc8-dev-platform-pagopa-it

azure-devops/nodo/06_pagopa-nodo-service.tf
=> chore: [PAGOPA-3055] Added env variable

azure-devops/crusc8/00_key_vault.tf, azure-devops/crusc8/00_secrets_crusc8.tf, azure-devops/crusc8/00_secrets_prod.tf, azure-devops/crusc8/00_service_connections.tf, azure-devops/crusc8/03_service_connections_aks.tf, azure-devops/crusc8/03_service_connections_docker_workload_identity.tf, azure-devops/crusc8/03_service_connections_tls_certificate.tf, azure-devops/crusc8/05_tlscert-crusc8-uat-platform-pagopa-it.tf
=> feat: Add pipeline uat cert cruscotto

azure-devops/shared/.terraform.lock.hcl, azure-devops/shared/00_secrets_shared.tf, azure-devops/shared/06_pagopa-anonymizer.tf, azure-devops/shared/99_main.tf
- Added anonymizer service to shared domain
---
=> feat: [PAGOPA-3105] Add anonymizer service to shared domain

azure-devops/core/00_monitor.tf, azure-devops/core/03_service_connections_tls_certificate.tf, azure-devops/core/05_tls_cert_platform_pagopa.it.tf, azure-devops/core/05_tlscert-prod-wisp2-pagopa-it.tf, azure-devops/core/99_variables.tf, azure-devops/core/README.md
=> feat: PAYMCLOUD-439 Cert diff enabled in prod env

azure-devops/iac/99_locals.tf
=> fix: Unified performance test scheduling
